server:
  port: 9002

spring:
  application:
    name: tt-ticket${unique-name:}-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/12306_ticket?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        import-check:
          enabled: false
      username: nacos
      password: nacos
    sentinel:
      transport:
        dashboard: localhost:8686
        port: 8719
  dynamic:
    thread-pool:
      nacos:
        data-id: hippo4j-nacos.yaml
        group: DEFAULT_GROUP
      config-file-type: yml
      executors:
        - thread-pool-id: 'select-seat-thread-pool-executor'
          alarm: false
          allow-core-thread-time-out: true
          blocking-queue: SynchronousQueue
          core-pool-size: 20
          maximum-pool-size: 40
          keep-alive-time: 9999
          rejected-handler: CallerRunsPolicy

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: tt_ticket${unique-name:}-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

framework:
  fastjson:
    safa-mode: true
  cache:
    redis:
      value-timeout: 16
      value-time-unit: days

feign:
  client:
    config:
      default:
        # 连接超时时间
        connectTimeout: 6000
        # 仅记录HTTP头信息
        loggerLevel: HEADERS
        # 读取超时时间
        readTimeout: 5000
  # apache http客户单，关闭
  httpclient:
    enabled: false
  # 高性能http客户端，打开
  okhttp:
    enable: true

# 暴露监听端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
