spring:
  cloud:
    gateway:
      routes:
        - id: tt-user-service
          uri: lb://tt-user${unique-name:}-service/api/user-service/**
          predicates:
            - Path=/api/user-service/**
          filters:
            # 过滤器的名字全称 TokenValidateGatewayFilterFactory，可以只写TokenValidate
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/user-service/passenger
                  - /api/user-service/query
                  - /api/user-service/logout
                  - /api/user-service/deletion
                  - /api/user-service/update

        - id: tt-ticket-service
          uri: lb://tt-ticket${unique-name:}-service/api/ticket-service/**
          predicates:
            - Path=/api/ticket-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/ticket-service/ticket/purchase
                  - /api/ticket-service/ticket/pay/query
                  - /api/ticket-service/ticket/cancel

        - id: tt-pay-service
          uri: lb://tt-pay${unique-name:}-service/api/pay-service/**
          predicates:
            - Path=/api/pay-service/**

        - id: tt-order-service
          uri: lb://tt-order${unique-name:}-service/api/order-service/**
          predicates:
            - Path=/api/order-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/order-service/order/ticket/query
                  - /api/order-service/order/ticket/page
                  - /api/order-service/order/ticket/self/page
