server:
  port: 9005

spring:
  application:
    name: tt-aggregation${unique-name:}-service
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.emv:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        import-check:
          enabled: false
      username: nacos
      password: nacos
    sentinel:
      transport:
        dashboard: localhost:8686
        port: 8719
  dynamic:
    thread-pool:
      nacos:
        data-id: hippo4j-nacos.yaml
        group: DEFAULT_GROUP
      config-file-type: yml
      executors:
        - thread-pool-id: 'select-seat-thread-pool-executor'
          alarm: false
          allow-core-thread-time-out: true
          blocking-queue: SynchronousQueue
          core-pool-size: 20
          maximum-pool-size: 40
          keep-alive-time: 9999
          rejected-handler: CallerRunsPolicy

  main:
    allow-bean-definition-overriding: true

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: tt_aggregation-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

pay:
  alipay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlr7nqd13XnbbAEv1TvnjJQLN0JHbBc3UA275AyjkEdyYWms1GDZDNd1MaPEVCjhRPmnIb8AtNILzseEHMOvWLf5Za30ZzL2TAn6IaGS2HC4Az/aX07ug4Qa9sm4Ftxz3njF4o9u6p2H7GVRd5Vmn80zGd+8iB6twMzbPLoi/15hus44vBwTAj9JERJMJWx9FnqT5HBodmhBphPemCJCk0Be9sIIh2KUawIv+FhL2yHGKxVw2CbXoubR5xLNh/5teX0jbsBysE+R3eZcENIdJGg+lAaXuFjt/uN08xfTtCB8iiAdtsHNyi7qBdSd7ym4Yzao+TVRGvaa1AqOofdVhsQIDAQAB
    app-id: 9021000137664028
    charset: UTF8
    format: json
    notify-url:
    private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCWvuep3XdedtsAS/VO+eMlAs3QkdsFzdQDbvkDKOQR3JhaazUYNkM13Uxo8RUKOFE+achvwC00gvOx4Qcw69Yt/llrfRnMvZMCfohoZLYcLgDP9pfTu6DhBr2ybgW3HPeeMXij27qnYfsZVF3lWafzTMZ37yIHq3AzNs8uiL/XmG6zji8HBMCP0kREkwlbH0WepPkcGh2aEGmE96YIkKTQF72wgiHYpRrAi/4WEvbIcYrFXDYJtei5tHnEs2H/m15fSNuwHKwT5Hd5lwQ0h0kaD6UBpe4WO3+43TzF9O0IHyKIB22wc3KLuoF1J3vKbhjNqj5NVEa9prUCo6h91WGxAgMBAAECggEAK2y9EYrRuy2j8tbuyJxlmaDQJzgNDwP3AjIym31pDdgtL0bY2auv+tFQFJ72P6ZviPoyGjcTDqB2kRRQ3P/jCAbQPY2hJACsW7iVlPUGHOIHq+DOZdkUBB7MAJ1/GfvHPRPlO9atU1B/ZBGQpuQH5KeGOMBzXiA9xxMP5cjQ8srqikbLFhEfngtfQrsGkn26lWO5+1kEZm6EkY15NXc2gWLgxNq88P2k8Ehn9cC8U8UzQvqJ5epotbWEVMYOnqotUjhJneGtB4FGpSwlxh4zzLwK9DK6n9I9+qAdsi5RD4XwdOVdXcSxX50vEnCVhiJgo41T+N0YHeNtGGW8uFgvjQKBgQD+OWKo7j6RzNr4z6i1yYPoO3bOywu3WfjX6LcHTbz+j2WQlruzezZFdZ5/5s/OJNhyF0qY3opAagkeHOY/+eplmlxEsE4CVrFnYbvuUchTLInnLtleNdBnD3Y+dyImSl/dKmlfIlTA8EdqbHyq2LMNfUhXmlCRzOFHYBWoioq6owKBgQCXzHmVhDUfI11NhDUJxJ2dYCpx3zg/xkGXYs+/3xEofSC+HYm2Rw0KA95Q4NzAkovAvZx/Xv4rKfuiBzRYuiok+69XYwWp7Su2FtCCZzNjZh0vKyWj7Ko1HMwGX0IIfvpMT4fsXlVhJr6K1AE1K5sx2kLozGlaZn37Cp3ghF8rmwKBgQDHvQiSF5Wbcit9H5K7OVflB4tiEE/lP9Buus3K9D4Qd1PiFTvmWWEbk7zzWsJcgcB5a2lV0EspLuZ4/VW+YDnUmEH0Sd0Qo1KBGl3QcfsFtlGnDL0F8xwJTTGnBG0VTowhNWhSsaOLb3181T3h8Z5Ec/F5uqmg1CsPrCN4J1m2JwKBgDvzcpVdWImKsv+5ViUcdM9BuqGscg+l4iPCz5/Mnn8qI/NRwSCvIPQyoOu6UxTvC6i8egFH6APuGcZdKAxeweRHTnGp1wPMenX4vrKxxXbdTmthlAUQpAxD6kQd/PtUAtB+nIT6oKe04I39uthf93QR6lj82iLs1ZZ/E+km/ls/AoGBAIkPITu195wltBBi6HGiA9FcYVeLZCKIpiqQehvSsnW+PvdfFjYXPEGx5TX3ZVYQZnJUKh3vlqEQWz969baMUhWLDOo42ChWsepUlbW61jDnvEwH0D0slU0AKPY/yvE7WzYcxA2Epb42MlioxEjB+u/R8d2frClspziRGJevCBiD
    server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    sign-type: RSA2

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aggregation:
  remote-url: http://127.0.0.1:${server.port}

framework:
  fastjson:
    safa-mode: true
  cache:
    redis:
      value-timeout: 50000
      bloom-filter:
        user-register:
          name: user_register_cache_penetration_bloom_filter${unique-name:}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
